In [42]:
from sklearn.datasets import load_digits
import pandas as pd

df = pd.read_csv('heart.csv')
df_sample = df
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [43]:
# Find and display null values in the DataFrame
null_values = df.isnull()
print("Null Values:")
print(null_values)

# Count and display the total number of null values in each column
null_counts = df.isnull().sum()
print("\nNull Value Counts:")
print(null_counts)

Null Values:
       Age    Sex  ChestPainType  RestingBP  Cholesterol  FastingBS
0    False  False          False      False        False      False  \
1    False  False          False      False        False      False
2    False  False          False      False        False      False
3    False  False          False      False        False      False
4    False  False          False      False        False      False
..     ...    ...            ...        ...          ...        ...
913  False  False          False      False        False      False
914  False  False          False      False        False      False
915  False  False          False      False        False      False
916  False  False          False      False        False      False
917  False  False          False      False        False      False

     RestingECG  MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
0         False  False           False    False     False         False
1         False  False           False    False     False         False
2         False  False           False    False     False         False
3         False  False           False    False     False         False
4         False  False           False    False     False         False
..          ...    ...             ...      ...       ...           ...
913       False  False           False    False     False         False
914       False  False           False    False     False         False
915       False  False           False    False     False         False
916       False  False           False    False     False         False
917       False  False           False    False     False         False

[918 rows x 12 columns]

Null Value Counts:
Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [45]:
# use one hot encoding to convert string values to integer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [47]:
# Apply label encoding to each column separately
columns_to_encode = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
for column in columns_to_encode:
    df[column] = le.fit_transform(df[column])

In [48]:
# Display the updated DataFrame
print(df)

     Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG
0     40    1              1        140          289          0           1  \
1     49    0              2        160          180          0           1
2     37    1              1        130          283          0           2
3     48    0              0        138          214          0           1
4     54    1              2        150          195          0           1
..   ...  ...            ...        ...          ...        ...         ...
913   45    1              3        110          264          0           1
914   68    1              0        144          193          1           1
915   57    1              0        130          131          0           1
916   57    0              1        130          236          0           0
917   38    1              2        138          175          0           1

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
0      172               0      0.0         2             0
1      156               0      1.0         1             1
2       98               0      0.0         2             0
3      108               1      1.5         1             1
4      122               0      0.0         2             0
..     ...             ...      ...       ...           ...
913    132               0      1.2         1             1
914    141               0      3.4         1             1
915    115               1      1.2         1             1
916    174               0      0.0         1             1
917    173               0      0.0         2             0

[918 rows x 12 columns]

In [49]:
import pandas as pd
import numpy as np

def remove_outliers_zscore(df, columns, threshold=3):
    z_scores = np.abs((df[columns] - df[columns].mean()) / df[columns].std())
    outliers = (z_scores > threshold).any(axis=1)
    cleaned_df = df[~outliers]
    return cleaned_df

# Example usage

columns_to_check = df.columns
cleaned_df = remove_outliers_zscore(df, columns_to_check)

# print("Original DataFrame:")
# print(df)
# print("\nCleaned DataFrame:")
# print(cleaned_df)

Original DataFrame:
     Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG
0     40    1              1        140          289          0           1  \
1     49    0              2        160          180          0           1
2     37    1              1        130          283          0           2
3     48    0              0        138          214          0           1
4     54    1              2        150          195          0           1
..   ...  ...            ...        ...          ...        ...         ...
913   45    1              3        110          264          0           1
914   68    1              0        144          193          1           1
915   57    1              0        130          131          0           1
916   57    0              1        130          236          0           0
917   38    1              2        138          175          0           1

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
0      172               0      0.0         2             0
1      156               0      1.0         1             1
2       98               0      0.0         2             0
3      108               1      1.5         1             1
4      122               0      0.0         2             0
..     ...             ...      ...       ...           ...
913    132               0      1.2         1             1
914    141               0      3.4         1             1
915    115               1      1.2         1             1
916    174               0      0.0         1             1
917    173               0      0.0         2             0

[918 rows x 12 columns]

Cleaned DataFrame:
     Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG
0     40    1              1        140          289          0           1  \
1     49    0              2        160          180          0           1
2     37    1              1        130          283          0           2
3     48    0              0        138          214          0           1
4     54    1              2        150          195          0           1
..   ...  ...            ...        ...          ...        ...         ...
913   45    1              3        110          264          0           1
914   68    1              0        144          193          1           1
915   57    1              0        130          131          0           1
916   57    0              1        130          236          0           0
917   38    1              2        138          175          0           1

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease
0      172               0      0.0         2             0
1      156               0      1.0         1             1
2       98               0      0.0         2             0
3      108               1      1.5         1             1
4      122               0      0.0         2             0
..     ...             ...      ...       ...           ...
913    132               0      1.2         1             1
914    141               0      3.4         1             1
915    115               1      1.2         1             1
916    174               0      0.0         1             1
917    173               0      0.0         2             0

[899 rows x 12 columns]